export const dataFieldCms = {
  createNewDataRequest: 'Create New Data Request',
  editDataRequest: 'Edit Data Request',
  localMarketLabel: 'Local Market',
  localMarketHint: 'Choose the market you wish to create this data request for',
  nameLabel: 'Data Request Name',
  backLabel:'Back To Clients',
  nameHint:
    "Make sure it's clear to help others identify it.Max 255 characters",
  briefLabel: 'Briefing',
  briefHint:
    'Tell us in detail what this data request is for, max 4000 characters',
  templateFileLabel: 'Add Tracker Template File',
  templateFileHint:
    'Only .xls, .xlsx, .csv, .xlsb, .xlsm, .xlt, .xltm, .xltx files in 20mb or less',
  uploadFileLabel:
    'To upload a new file,drag and drop you file below or browse using the link',
  uploadFileLargeMessage: 'File must be less than 20MB',
  labelFileTypeNotAllowed: 'File must be of type .xls, .xlsx, .csv, .xlsb, .xlsm, .xlt, .xltm, .xltx',
  uploadButtonText:'Upload New File',
  actualDataLabel: 'Actual Data',
  versionHistoryTitle:'Version History',
  actualDataHint: 'Number of months of actual productivity data',
  forecastDataLabel: 'Forecast Data',
  forecastDataHint: 'Number of months of forecasted productivity data',
  dueDateLabel: 'Due Date',
  dueDateHint: 'Enter the date that you need this data request by',
  assignToLabel: 'Assign To',
  assignToHint: `Only the person or team you assign this to will have access. Once you click 'Create' ,
  they will be sent email notifications asking them to fill in the data request.`,
  create: 'Create',
  upload:'Upload',
  cancel: 'Cancel',
  productivityDatarequestHeading: 'Productivity Data Requests',
  productivityDatarequestCaption: ' The ongoing and complete productivity data requests created for this client',
  selectPlaceHolder: 'Please select',
  datePlaceHolder: 'Date',
  viewDetails: 'View Details',
  viewClientsHeading: 'My Clients',
  viewClientsCaption: 'Choose the client you wish to view',
  completeLabel: 'Complete',
  ongoingLabel: 'Ongoing',
  emptyProductivityDatarequestCaption:
    'There are currently no active Productivity data requests',
  emptyLabel: 'Create New Data Request',
  edit: 'Edit',
  actual: 'Actuals',
  forecast: 'Forecast',
  overdue: 'Overdue',
  ongoing: 'Ongoing',
  complete: 'Complete',
  lastUpdate: 'Last Update',
  moveToComplete: 'Move to Complete',
  moveToOnGoing: 'Move to Ongoing',
  delete: 'Delete',
  deletePopConfimationMessage:'Once deleted, this data request will no longer be available.',
  deleteButtonCancelMessage:'No, Cancel',
  deleteButtonDeleteMessage:'Yes, Delete',
  popUpTitle:'Are you sure you want to delete?',
  emptyCompletedProductivityDatarequestCaption:
    'No Productivity data requests have been moved to this section yet.',
  editRequest: 'Edit request',
  save: 'Save',
  productivityRequest: 'Productivity Request',
  showMore: 'Show more',
  reportingYear: 'Reporting Year',
  productivityDataRequested: 'Productivity data requested',
  actualCapitalized: 'Actual',
  forecastCapitalized: 'Forecast',
  dueBy: 'Due by',
  assignedTo: 'Assigned to',
  trackerTemplate: 'Tracker Template',
  close: 'Close',
  reportingYearLabel: 'Reporting Year',
  reportingYearHint: 'The reporting year this data request is for',
  toastRequestCreated: 'Data request created',
  toastRequestEdited: 'Data request edited',
  toastRequestDeleted: 'Data request deleted',
  toastFileUploaded: 'File Uploaded',
  toastMovedToOngoing: 'Data request moved to Ongoing',
  toastMovedToComplete: 'Data request moved to Complete',
  currentVersionText:'current version',
  loadMoreText:'Load more',
  uploadFileErrorMessage:'Upload Tracker Template',
}
