export const dataFieldCms = {
  createNewDataRequest: 'Create new data request',
  editDataRequest: 'Edit data request',
  localMarketLabel: 'Local Market',
  localMarketHint: 'Choose the market you want to create a data request',
  nameLabel: 'Name',
  nameHint: 'Give your data request a name that will be viewed by all recipients',
  briefLabel: 'Briefing',
  briefHint: 'Tell us in detail what this data request is for, max 4000 characters',
  templateFileLabel: 'Attach tracker template file',
  templateFileHint: 'Only .xls, .xlsx, .csv, .xlsb, .xlsm, .xlt, .xltm, .xltx files in 20mb or less',
  actualDataLabel: 'Actual Productivity Data',
  actualDataHint: 'Select the number of months data required',
  forecastDataLabel: 'Forecast Productivity Data',
  forecastDataHint: 'Select the number of months data required',
  dueDateLabel: 'Due Date',
  dueDateHint: 'Enter the date that you require the data request by',
  assignToLabel: 'Assign To',
  assignToHint: `Only the person or team you assign this to will have access. Once you click 'Create' ,
  they will be sent email notifications asking them to fill in the data request.`,
  create: 'Create',
  cancel: 'Cancel',
  productivityDatarequestHeading: 'Productivity data requests',
  productivityDatarequestCaption: ' The ongoing and complete productivity data requests created for this client',
  selectPlaceHolder: 'Please Select',
  datePlaceHolder: 'Date',
  viewDetails : 'View Details',
  viewClientsHeading : 'My clients',
  viewClientsCaption : 'Choose the client you wish to view',
  completeLabel: 'Complete',
  ongoingLabel: 'Ongoing',
  emptyProductivityDatarequestCaption: 'There are currently no active Productivity data requests',
  emptyLabel: 'Create new data request',
  edit: 'Edit',
}
