FROM nginx:stable

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx.conf /etc/nginx/nginx.conf.template
COPY ./nginx-conf.sh /usr/local/bin/nginx-conf.sh
RUN chmod +x /usr/local/bin/nginx-conf.sh
COPY ./build/ /var/www

# Default configuration
ENV PORT 80
ENV SERVER_NAME _

# prepare and launch nginx.conf
CMD /usr/local/bin/nginx-conf.sh && nginx -g 'daemon off;'
