FROM timbru31/java-node
WORKDIR /ops
COPY codecept-tests .
RUN apt-get update && apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
&& echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
&& apt-get update -qqy \
&& apt-get -qqy install google-chrome-stable jq gettext \
&& rm /etc/apt/sources.list.d/google-chrome.list \
&& rm -rf /var/lib/apt/lists/* /var/cache/apt/* \
&& sed -e 's|"$HERE\/chrome"|"$HERE\/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
RUN wget https://aka.ms/downloadazcopy-v10-linux && tar -zxvf downloadazcopy-v10-linux && cd azcopy_linux_amd64_* && cp azcopy .. && cd ..
RUN npm i
RUN npm install allure-commandline --save-dev
RUN npm install codeceptjs-rphelper@1.1.12 --save
COPY run_tests.sh .
RUN chmod +x run_tests.sh





