{{- if .Values.ingress.enabled -}}
{{- $fullName := include "dan-productivity-mgr-ui.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "dan-productivity-mgr-ui.name" . }}
    chart: {{ template "dan-productivity-mgr-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class}}
    nginx.ingress.kubernetes.io/enable-modsecurity: "false"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
      Include /etc/nginx/modsecurity/modsecurity.conf
      SecAuditLog /var/log/modsec/audit.log
      SecAuditLogParts ABCEFGHJKZ
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: 80
  {{- end }}
{{- end }}
